add header visual part
velogitara/PetLy-project-Front pull request #5
Opened 2022-11-10 17:59 UTC by RomanPyryn

2022-11-10 20:10 UTC, velogitara commented
смотри, наверное нужно слелать вложенность одного уровня 
![image](https://user-images.githubusercontent.com/93466688/201195835-58493c8b-0f01-4b27-b6dd-990168a71a73.png)

2022-11-10 20:25 UTC, velogitara requested changes

2022-11-10 20:25 UTC, velogitara commented on src/components/Header/Navigation/Nav/Nav.jsx
> +    <div>
<nav> вроде linki нужно не в див обернуть а в <nav>

2022-11-10 20:25 UTC, velogitara commented on src/components/Header/Header.styled.jsx
> +export const HeaderBox = styled.div`
если я правильно помню тут дожен быть styler.header

2022-11-11 13:36 UTC, RomanPyryn commented on src/components/Header/Header.styled.jsx
> +export const HeaderBox = styled.div`
100% !!!!

2022-11-12 07:31 UTC, velogitara approved these changes

2022-11-12 07:31 UTC, merged